using System.Text;

namespace WhiteDependencyInjection
{
    public sealed class SourceGeneratorBuilder
    {
        private readonly StringBuilder _sb = new("// <auto-generated/>\n");

        public SourceGeneratorBuilder Append(string line)
        {
            _sb.Append(line);
            return this;
        }
        
        public SourceGeneratorBuilder AppendLine(string line)
        {
            _sb.AppendLine(line);
            return this;
        }

        public SourceGeneratorBuilder Append(char symbol)
        {
            _sb.Append(symbol);
            return this;
        }
        
        public SourceGeneratorBuilder AppendLine()
        {
            _sb.AppendLine();
            return this;
        }

        public string Build() => _sb.ToString();
    }
}