using System.Text;

namespace WhiteDependencyInjection
{
    public sealed class SourceGeneratorBuilder
    {
        private readonly StringBuilder _sb = new("// <auto-generated/>\n");

        public SourceGeneratorBuilder Append(string line)
        {
            _sb.Append(line);
            return this;
        }

        public SourceGeneratorBuilder Append(char symbol)
        {
            _sb.Append(symbol);
            return this;
        }

        public SourceGeneratorBuilder Append(string line, params object[] args)
        {
            _sb.AppendFormat(line, args);
            return this;
        }

        public string Build() => _sb.ToString();
    }
}